# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'Odnako' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseCore'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'SDWebImage'
# pod 'FSCalendar'
  # Pods for Odnako

end
